apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }} 
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: frontend
        image: "{{ .values.image.repository }}/{{ .Values.appName }}:{{ .Values.appVersion }}"
        ports:
        - containerPort: 80